# Generated by Django 3.2.21 on 2023-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='max_display_count',
            field=models.IntegerField(default=3),
        ),
    ]
