# Generated by Django 3.2.21 on 2023-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_max_display_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.CharField(max_length=64)),
                ('limit', models.CharField(max_length=32)),
            ],
        ),
    ]
